---
version: "3.7"

services:
  coredns:
    image: xvxd4sh/coredns:latest
    container_name: coredns
    hostname: coredns_megazord
    init: true
    restart: on-failure:5
    volumes:
      - ./src/coredns/config:/root

  apache2:
    image: xvxd4sh/apache2
    container_name: apache
    init: true
    restart: on-failure:5
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - ./src/apache2/payload/:/var/www/uploads/
      - ./src/apache2/src/:/var/www/html
      - ./src/apache2/apache2.conf:/etc/apache2/apache2.conf
      - ./src/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.202.0/24
