---
version: "3.7"

services:
  coredns:
    image: xvxd4sh/coredns:latest
    container_name: coredns
    hostname: coredns_megazord
    init: true
    restart: on-failure:5
    ports:
      - target: 53
        published: 53
        host_ip: ${HOST_IP}
        protocol: udp
        mode: host
    volumes:
      - ./src/coredns/config:/root
    networks:
      appNetwork:
        ipv4_address: 172.19.0.3

  apache:
    image: xvxd4sh/apache2:latest
    container_name: apache
    init: true
    restart: on-failure:5
    ports:
      - target: 80
        published: 80
        host_ip: ${HOST_IP}
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        host_ip: ${HOST_IP}
        protocol: tcp
        mode: host
    volumes:
      - ./src/apache2/payload/:/var/www/uploads/
      - ./src/apache2/.htaccess:/var/www/html/.htaccess
      - ./src/apache2/apache2.conf:/etc/apache2/apache.conf
    networks:
      appNetwork:
        ipv4_address: 172.19.0.4

  cobalt:
    image: debian:11
    container_name: cobalt
    init: true
    restart: on-failure:5
    command: >
      bash -c " apt-get update > /dev/null 2>&1 &&
                apt-get install -y libfreetype6 > /dev/null 2>&1 &&
                apt-get install -y default-jdk > /dev/null 2>1 &&
                cd /opt/cobaltstrike/ &&
                ./teamserver ${C2_IP} ${PASSWORD} ${C2_PROFILE} ${KILLDATE}"
    ports:
      - target: 50050
        published: 50050
        host_ip: ${HOST_IP}
        protocol: tcp
        mode: host
    expose:
      - "53"
      - "443"
      - "80"
    volumes:
      - /opt/cobaltstrike/:/opt/cobaltstrike/
      - ./${C2_PROFILE}:/opt/cobaltstrike/${C2_PROFILE}
    networks:
      appNetwork:
        ipv4_address: 172.19.0.5

networks:
  appNetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
