---
version: "3.7"

services:
  coredns:
    image: xvxd4sh/coredns:latest
    container_name: coredns
    hostname: coredns_megazord
    init: true
    restart: on-failure:5
    volumes:
      - ./src/coredns/config:/root
    networks:
      appNetwork:
        ipv4_address: 172.19.0.3

  apache:
    image: xvxd4sh/apache2:latest
    container_name: apache
    init: true
    restart: on-failure:5
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - ./src/apache2/payload/:/var/www/uploads/
      - ./src/apache2/:/var/www/html
      - ./src/apache2/apache2.conf:/etc/apache2/apache2.conf
      - ./src/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      appNetwork:
        ipv4_address: 172.19.0.4

  cobalt:
    image: debian:11
    container_name: cobalt
    init: true
    restart: on-failure:5
    command: bash -c "echo hello world"
    ports:
      - "50050:50050"
    expose:
      - "53"
      - "443"
      - "80"
    volumes:
      - /opt/cobaltstrike/:/opt/cobaltsrike/
    networks:
      appNetwork:
        ipv4_address: 172.19.0.5

networks:
  appNetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
