---
version: "3.7"

services:
  coredns:
    image: xvxd4sh/coredns:latest
    container_name: coredns
    hostname: coredns_megazord
    init: true
    restart: on-failure:5
    ports:
      - target: 53
        published: 53
        protocol: udp
        mode: host
    volumes:
      - ./src/coredns/config:/root
    networks:
      appNetwork:
        ipv4_address: 172.19.0.3

  apache:
    image: xvxd4sh/apache2:latest
    container_name: apache
    init: true
    restart: on-failure:5
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /opt/cobaltstrike/uploads:/var/www/uploads/
      - ./src/apache2/.htaccess:/var/www/html/.htaccess
      - ./src/apache2/apache2.conf:/etc/apache2/apache2.conf
      - ./src/apache2/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
      - ./src/secrets/cobalt.cert:/etc/ssl/certs/cobalt.cert
      - ./src/secrets/cobalt.key:/etc/ssl/private/cobalt.key
    networks:
      appNetwork:
        ipv4_address: 172.19.0.4

  cobalt:
    image: xvxd4sh/java-debian11
    container_name: cobalt
    depends_on:
      - apache
      - coredns
    init: true
    restart: on-failure:5
    command: >
      bash -c "echo 'teamserver starting, please do not close this window' &&
               cd /opt/cobaltstrike/ &&
               ./teamserver ${C2_IP} ${PASSWORD} ${C2_PROFILE} ${KILLDATE}"
    ports:
      - target: 50050
        published: 50050
        protocol: tcp
        mode: host
    expose:
      - "53"
      - "443"
      - "80"
    volumes:
      - /opt/cobaltstrike/:/opt/cobaltstrike/
      - ./${KEYSTORE}:/opt/cobaltstrike/${KEYSTORE}
      - ./${C2_PROFILE}:/opt/cobaltstrike/${C2_PROFILE}
    networks:
      appNetwork:
        ipv4_address: 172.19.0.5

networks:
  appNetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
